### ISSUE TITLE
Decoupled Editor - Indent-Block plugin doesn't seem to work

### ISSUE THREAD

**Issue by spra85** [ckeditor/ckeditor5-build-decoupled-document#24] opened 2019-09-27 15:02 UTC
Steps to recreate were: 

:one: Git clone the decoupled-document build (https://github.com/ckeditor/ckeditor5-build-decoupled-document)
:two: npm install --save @ckeditor/ckeditor5-indent
:three: Modify source `src/ckeditor.js` build

```
import Indent from '@ckeditor/ckeditor5-indent/src/indent';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock';
```

Add to builtInPlugins:
```
IndentBlock,
Indent,
```

Add to toolbar items config:
```
'outdent',
'indent',
```

Run the local sample/index.html provided in this repo:
![image](https://user-images.githubusercontent.com/423943/65779640-c35d3200-e10d-11e9-9630-7f347766a2b9.png)

The indent/outdent buttons appear but don't seem to work.  The exact same set of steps above worked fine with the Classic editor (https://github.com/ckeditor/ckeditor5-build-classic), so I'm confused why they wouldn't work with the Decoupled Document editor.

**Comment by Mgsy** [comment] 2019-09-30 09:56
Hello @spra85, I've followed your steps and I'm not able to reproduce the issue. 

![bug_cke5](https://user-images.githubusercontent.com/20988892/65868797-4df59980-e379-11e9-8b57-0a998163e166.gif)

Do you have any errors in the console?

**Comment by spra85** [comment] 2019-09-30 16:39
@Mgsy, weird.  There are no errors in the console - It's definitely possible that I've messed something small up.  It's still not working for me, and I've pushed up a forked version that you can access here: https://github.com/spra85/ckeditor5-build-decoupled-document

with the diff: 
https://github.com/spra85/ckeditor5-build-decoupled-document/commit/92d934bcb77bd80699b2a4986db4fe89bb5d8812

**Comment by Mgsy** [comment] 2019-10-01 13:04
Thanks for a sample, I can reproduce it. 

I noticed that you add `Indent` and `IndentBlock` at the beginning of the `builtinPlugins` array, after moving it to the end of the array, it started working for me. Can you confirm that this solves your issue?

**Comment by spra85** [comment] 2019-10-01 14:24
@Mgsy, you're right.  It does work at the end of the array; after digging further, it looks like if it is defined in the `builtInPlugins` array after the `Heading` plugin, it works.  If it's before that plugin, it does not work.  Do you consider this a bug in the way plugins are initialized within the editor, or a misconfiguration issue?

**Comment by Mgsy** [comment] 2019-10-01 14:41
I've investigated it a bit and have the same conclusions. Additionally, it looks like it also concerns the `Paragraph` plugin. It definitely should be checked. I'll close this issue and open another one in a proper repository. Thanks for bringing it up to us!

**Closed by Mgsy** 2019-10-01 14:41 UTC
Labels: pending:feedback
